name: EsteiraDeploy
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Meu primeiro Pipeline!

  deploy-TU:
    runs-on: ubuntu-latest
    environment: 
      name: TU
      url: 'mazielluiz.com'
    needs: build
    steps:
      - name: Run a one-line script
        run: echo Deploy TU

  deploy-TI:
    runs-on: ubuntu-latest
    environment: 
      name: TI
      url: 'mazielluiz.com'
    needs: deploy-TU
    steps:
      - name: Run a one-line script
        run: echo Deploy TI

  deploy-HO:
    runs-on: ubuntu-latest
    environment: 
      name: HO
      url: 'mazielluiz.com'
    needs: deploy-TI
    steps:
      - name: Run a one-line script
        run: echo Deploy HO

